In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2077, 4111, 2703, 2473],
 [2077, 4111, 2703, 7442],
 [2077, 1317, 2703, 7448],
 [5857, 1060, 6661, 5125, 7252],
 [5857, 1060, 6661, 5125, 4536],
 [699, 2077, 7613, 2703, 8569],
 [7374, 4365, 1411, 5125]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 2077, 4111, 2703, 2473],
       [   0,    0,    0,    0, 2077, 4111, 2703, 7442],
       [   0,    0,    0,    0, 2077, 1317, 2703, 7448],
       [   0,    0,    0, 5857, 1060, 6661, 5125, 7252],
       [   0,    0,    0, 5857, 1060, 6661, 5125, 4536],
       [   0,    0,    0,  699, 2077, 7613, 2703, 8569],
       [   0,    0,    0,    0, 7374, 4365, 1411, 5125]], dtype=int32)

In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step


array([[[ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [-0.0287814 ,  0.03484396, -0.04988769, -0.0343608 ,
          0.0335424 ,  0.00295273, -0.02909598, -0.00055385,
         -0.02379345, -0.03562168],
        [-0.04765264, -0.03684377,  0.00994166, -0.04207234,
          0.03302795,  0.01006203, -0.04983846,  0.04865228,
          0.04911647,  0.00897243],
        [ 0.04079011, -0.01424799, -0.02417745,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 2077, 4111, 2703, 2473], dtype=int32)

In [17]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


array([[[ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [ 0.03017889, -0.03549913, -0.03306822, -0.00753311,
         -0.03433936, -0.04279102,  0.0299654 , -0.02875748,
         -0.04316018,  0.01387774],
        [-0.0287814 ,  0.03484396, -0.04988769, -0.0343608 ,
          0.0335424 ,  0.00295273, -0.02909598, -0.00055385,
         -0.02379345, -0.03562168],
        [-0.04765264, -0.03684377,  0.00994166, -0.04207234,
          0.03302795,  0.01006203, -0.04983846,  0.04865228,
          0.04911647,  0.00897243],
        [ 0.04079011, -0.01424799, -0.02417745,  0.0